In [30]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import pickle

In [2]:
data_path = '../data/'
train = pickle.load(open('../data/train', 'r'))
test = pickle.load(open('../data/test', 'r'))

In [9]:
data = pd.concat([train, test])

In [13]:
print train.msno.count()
print test.msno.count()
print data.msno.count() == train.msno.count() + test.msno.count()

7377418
2556790
True


In [14]:
data = data[]

Empty DataFrame
Columns: [artist_name, bd, city, composer, expiration_date, expiration_month, expiration_year, gender, genre_ids, id, language, lyricist, msno, registered_via, registration_date, registration_init_time, registration_month, registration_year, song_country, song_id, song_length, song_name, song_year, source_screen_name, source_system_tab, source_type, target]
Index: []

[0 rows x 27 columns]


In [16]:
users = data.msno.unique()

In [17]:
items = data.song_id.unique()

In [20]:
from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# le.fit(users)
# train['user'] = le.transform(train['msno'])
# test['user'] = le.transform(test['msno'])

In [21]:
# le = LabelEncoder()
# le.fit(items)
# train['items'] = le.transform(train['song_id'])
# test['items'] = le.transform(test['song_id'])

In [23]:
from tqdm import tqdm
cols = list(train.columns)
cols.remove('target')

for col in tqdm(cols):
    try:
        if train[col].dtype == 'object':
            train[col] = train[col].apply(str)
            test[col] = test[col].apply(str)

            le = LabelEncoder()
            train_vals = list(train[col].unique())
            test_vals = list(test[col].unique())
            le.fit(train_vals + test_vals)
            train[col] = le.transform(train[col])
            test[col] = le.transform(test[col])

            print(col + ': ' + str(len(train_vals)) + ', ' + str(len(test_vals)))
    except:
        print (col, type(train[col]))
        break

  4%|▎         | 1/27 [00:47<20:36, 47.54s/it]

msno: 30755, 25131


  7%|▋         | 2/27 [02:28<30:55, 74.20s/it]

song_id: 359966, 224753


 11%|█         | 3/27 [02:55<23:24, 58.51s/it]

source_system_tab: 9, 9


 15%|█▍        | 4/27 [03:27<19:52, 51.83s/it]

source_screen_name: 21, 23


 19%|█▊        | 5/27 [03:57<17:26, 47.55s/it]

source_type: 13, 13


 26%|██▌       | 7/27 [04:30<12:51, 38.58s/it]

genre_ids: 573, 502


 30%|██▉       | 8/27 [05:18<12:36, 39.80s/it]

artist_name: 40583, 27564


 33%|███▎      | 9/27 [06:18<12:37, 42.06s/it]

composer: 76065, 52307


 37%|███▋      | 10/27 [06:59<11:53, 42.00s/it]

lyricist: 33889, 24911


 44%|████▍     | 12/27 [08:19<10:24, 41.66s/it]

song_name: 234112, 154708


 48%|████▊     | 13/27 [08:47<09:28, 40.59s/it]

song_country: 110, 97


100%|██████████| 27/27 [09:09<00:00, 20.36s/it]

gender: 3, 3


In [24]:
pickle.dump(train, open('../data/train1', 'w'))

In [25]:
print 'done'

done


In [26]:
pickle.dump(test, open('../data/test2', 'w'))

In [27]:
print 'done'

done


In [28]:
print data.msno.nunique()
print data.song_id.nunique()

34403
419839


In [31]:
X = np.array(train.drop(['target'], axis=1))
y = train['target'].values

X_test = np.array(test.drop(['id'], axis=1))
ids = test['id'].values

X_train, X_valid, y_train, y_valid = train_test_split(X, y, \
    test_size=0.2, random_state=0)

In [32]:
X_train1, X_valid1, y_train1, y_valid1 = train_test_split(X, y, \
    test_size=0.2, random_state=0)

In [41]:
pickle.dump(X_train, open('../data/X_train', 'w'))
pickle.dump(X_valid, open('../data/X_valid', 'w'))
pickle.dump(y_train, open('../data/y_train', 'w'))
pickle.dump(y_valid, open('../data/y_valid', 'w'))

In [42]:
print X_train[0]

[  6.28600000e+03   1.91125000e+05   4.00000000e+00   9.00000000e+00
   4.00000000e+00   2.20682000e+05   3.72000000e+02   3.34900000e+03
   6.62710000e+04   2.28800000e+04   3.10000000e+01   2.31606000e+05
   1.02000000e+02   2.01400000e+03   3.00000000e+00   5.10000000e+01
   2.00000000e+00   9.00000000e+00   2.00602260e+07   3.00000000e+01
   2.00600000e+03   2.00000000e+00   2.60000000e+01   2.01700000e+03
   1.00000000e+00   6.28600000e+03   1.91125000e+05]


In [43]:
train.head(1)

msno  song_id  source_system_tab  source_screen_name  source_type  target  \
0  9176    86884                  2                   8            7       1   

   song_length  genre_ids  artist_name  composer  ...    registered_via  \
0     206471.0        308         3785     16654  ...                 7   

   registration_init_time  expiration_date  registration_year  \
0                20120102                5               2012   

   registration_month  registration_date  expiration_year  expiration_month  \
0                   1                  2             2017                10   

   user  items  
0  9176  86884  

[1 rows x 28 columns]

In [44]:
userName_ID_map = {}
k = 0
for user in data.msno.unique():
    userName_ID_map[user] = k
    k += 1

In [45]:
print len(userName_ID_map)

34403


In [46]:
songName_ID_map = {}
k = 0
for song_id in data.song_id.unique():
    songName_ID_map[song_id] = k
    k += 1

In [47]:
print len(songName_ID_map)

419839


In [48]:
pickle.dump(userName_ID_map, open('../data/userName_ID_map', 'wb'))
pickle.dump(songName_ID_map, open('../data/songName_ID_map', 'wb'))

In [76]:
nums = np.array([[1, 2, 1], [3, 6, 16], [3, 3, 3]])

In [77]:
print np.shape(nums)

(3, 3)


In [84]:
D = np.diag(np.sum(nums, axis = 1))

In [85]:
print D

[[ 4  0  0]
 [ 0 25  0]
 [ 0  0  9]]


In [80]:
print nums

[[ 1  2  1]
 [ 3  6 16]
 [ 3  3  3]]


In [97]:
D1 = D**(0.5)
print D1

[[ 2.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0.  3.]]


In [95]:
for i in range(D.shape[0]):
    D1[i,i] = 1.0 / D1[i,i]

In [98]:
print D1

[[ 2.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0.  3.]]
